2025-03-26 09:28:26,325 : INFO : root : Loading config.
2025-03-26 09:28:26,560 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2025-03-26 09:28:26,560 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-26 09:28:26,560 : INFO : ConfigProcessor : Loading config from file /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2025-03-26 09:28:26,605 : INFO : ConfigProcessor : Loading config: /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2025-03-26 09:28:26,606 : INFO : ConfigProcessor : Loading config from file /home/pinpi/toedragons-pinball/config/config.yaml.
2025-03-26 09:28:26,608 : INFO : ConfigProcessor : Loading config: /home/pinpi/toedragons-pinball/config/config.yaml
2025-03-26 09:28:26,608 : INFO : ConfigProcessor : Config file cache created: /tmp/9121053a167b3a0609222a4623987891.mpf_cache
2025-03-26 09:28:26,691 : INFO : ConfigProcessor : Loading config from file /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml.
2025-03-26 09:28:26,692 : INFO : ConfigProcessor : Loading config: /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml
2025-03-26 09:28:26,693 : INFO : ConfigProcessor : Config file cache created: /tmp/66ef204c87633dc02ca3efd475778ed9.mpf_cache
2025-03-26 09:28:26,693 : INFO : ConfigProcessor : Loading config from file /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml.
2025-03-26 09:28:26,695 : INFO : ConfigProcessor : Loading config: /home/pinpi/pinpi/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml
2025-03-26 09:28:26,695 : INFO : ConfigProcessor : Config file cache created: /tmp/74f2825223a7abe8c76a0d15a1753cf2.mpf_cache
2025-03-26 09:28:26,695 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev7
2025-03-26 09:28:26,695 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2025-03-26-09-28-26-mpf-pinpi.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/pinpi/toedragons-pinball/logs/2025-03-26-09-28-26-mpf-pinpi.log'}
2025-03-26 09:28:26,695 : INFO : Machine : MPF path: /home/pinpi/pinpi/lib/python3.11/site-packages/mpf
2025-03-26 09:28:26,695 : INFO : Machine : Machine path: /home/pinpi/toedragons-pinball
2025-03-26 09:28:26,695 : INFO : Machine : Platform: linux
2025-03-26 09:28:26,695 : INFO : Machine : Python executable location: /home/pinpi/pinpi/bin/python
2025-03-26 09:28:26,695 : INFO : Machine : Python version: 3.11.2 (64-bit)
2025-03-26 09:28:26,696 : INFO : Machine : Initializing MPF...
2025-03-26 09:28:26,716 : ERROR : ConfigValidator : Your config contains a value for the setting "fast:ports", but this is not a valid setting name.
2025-03-26 09:28:26,717 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 686, in initialize_mpf
    raise init.exception()
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 248, in initialize
    await self.initialize_core_and_hardware()
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 234, in initialize_core_and_hardware
    self._load_hardware_platforms()
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 490, in _load_hardware_platforms
    self.add_platform(hardware_platform)
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 620, in add_platform
    self.hardware_platforms[name] = hardware_platform(self)
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/platforms/fast/fast.py", line 59, in __init__
    self.config = self.machine.config_validator.validate_config("fast", self.machine.config['fast'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Your config contains a value for the setting "fast:ports", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2025-03-26 09:28:26,721 : INFO : root : MPF run loop ended.
